
//import { Inter } from "next/font/google";
import localFont from "next/font/local"
const myFont = localFont ({src : "./Fonts/Bahij_TheSansArabic-ExtraBold.ttf"})
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import SpaceOrange4 from './assets/SpaceOrange4.jpeg'




//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
