import {
    RxCrop,
    RxDesktop,
    RxPencil2,
    RxReader,
    RxRocket,
    RxAccessibility,
  } from "react-icons/rx";
  
  import SpaceOrange4 from '../assets/SpaceOrange4.jpeg'
  import Rick from '../assets/Season_eleven_rick_grimes.png'

  
  export const ServiceData = [
    {
      id : 1,
      url : "مسلسل-the-walking-dead",
      rate: 8.6,
      title: "the walking deadمسلسل ",
      content: "مسلسل ذا ووكينج ديد زومبي واثارة مجموعة تحاول الهروب من الموت حيث تواجههم صعوبات في رحلتهم", 
      backgroundImage: "https://m.media-amazon.com/images/I/813QE3zGj4L._AC_UF1000,1000_QL80_.jpg",
      
    },
    {
      id : 2,
      url : "مسلسل-prison-break",
      rate: 10,
      title: "مسلسل prison break",
      content: "يقوم مايكل سكوفيلد باقحام نفسه ويدخل السجن لينقذ اخاه ويحاول الهرب من السجن وتواجههم بعض الصعوبات",
      backgroundImage: "https://m.media-amazon.com/images/I/51S7PUcgb2L._AC_UF894,1000_QL80_.jpg",
    },
    {
      id : 3,
      url : "مسلسل-Game-Of-Throans",
      rate: 9.8,
      title: "Game Of Throans مسلسل",
      content: "صراع العروش هو مسلسل تقوم احداثه في عصر التنانين تحارب الممالك السبع للحصول على العرش الحديدي",
      backgroundImage: "https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
    },
    {
      id : 4,
      url : "مسلسل-breaking-bad",
      rate : 6,
      title: "bp مسلسل      ",
      content: "اختلال ضال يحكي قصة والتر وايت (براين كرانستون)، معلم مادة الكيمياء في إحدى المدارس الثانوية، والذي يتم تشخيصه بأنه مصابٌ بمرض سرطان الرئة غير قابلٍ للعلاج في بداية المسلسل",
      backgroundImage: "https://static.displate.com/270x380/displate/2021-02-09/265eb60ddb098e964211e1cfc5c787f6_adfafdfc684d9a6c5e90f7d9e584fa82.jpg",
    },
    {
      id : 5,
      url : "مسلسل-12-monkeys",
      rate: 7.5,
      title: "12 monkeys مسلسل ",
      content: "تتبع المسلسل رحلة مسافر زمني أتى من مستقبل ما بعد نهاية الأرض ودمارها، ليظهر في يومنا الحاضر خلال مهمة لتحديد موقع وباء قاتل من شأنه أن يَدمّر الجنس البشري بالكامل",
      backgroundImage: "https://m.media-amazon.com/images/M/MV5BMTkwOTcxNzMzOV5BMl5BanBnXkFtZTgwODYxNjg0ODE@._V1_.jpg",
    },
    {
      id : 6,
      url : " فيلم-spiderman",
      rate: 3,
      title: "spiderman فيلم ",
      content: "يتناول الفيلم قصة طالب في المرحلة الثانوية يُدعي بيتر باركر. يعضه عنكبوت مُعالج جينياً، فيكتسب قدرات خارقة نتيجة امتزاج كود العنكبوت الجيني بالكود الخاص به",
      backgroundImage: "https://m.media-amazon.com/images/I/91ROGy7tYGL._AC_UF1000,1000_QL80_.jpg",
    },
    {
      id : 7,
      url : "مسلسل-the-walking-dead",
      rate: 8.6,
      title: "the walking deadمسلسل ",
      content: "مسلسل ذا ووكينج ديد زومبي واثارة مجموعة تحاول الهروب من الموت حيث تواجههم صعوبات في رحلتهم", 
      backgroundImage: "https://m.media-amazon.com/images/I/813QE3zGj4L._AC_UF1000,1000_QL80_.jpg",
      
    },
    {
      id : 8,
      url : "مسلسل-prison-break",
      rate: 10,
      title: "مسلسل prison break",
      content: "يقوم مايكل سكوفيلد باقحام نفسه ويدخل السجن لينقذ اخاه ويحاول الهرب من السجن وتواجههم بعض الصعوبات",
      backgroundImage: "https://m.media-amazon.com/images/I/51S7PUcgb2L._AC_UF894,1000_QL80_.jpg",
    },
    {
      id : 9,
      url : "مسلسل-Game-Of-Throans",
      rate: 9.8,
      title: "Game Of Throans مسلسل",
      content: "صراع العروش هو مسلسل تقوم احداثه في عصر التنانين تحارب الممالك السبع للحصول على العرش الحديدي",
      backgroundImage: "https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
    },
    {
      id : 10,
      url : "مسلسل-breaking-bad",
      rate : 6,
      title: "bp مسلسل      ",
      content: "اختلال ضال يحكي قصة والتر وايت (براين كرانستون)، معلم مادة الكيمياء في إحدى المدارس الثانوية، والذي يتم تشخيصه بأنه مصابٌ بمرض سرطان الرئة غير قابلٍ للعلاج في بداية المسلسل",
      backgroundImage: "https://static.displate.com/270x380/displate/2021-02-09/265eb60ddb098e964211e1cfc5c787f6_adfafdfc684d9a6c5e90f7d9e584fa82.jpg",
    },
    {
      id : 11,
      url : "مسلسل-12-monkeys",
      rate: 7.5,
      title: "12 monkeys مسلسل ",
      content: "تتبع المسلسل رحلة مسافر زمني أتى من مستقبل ما بعد نهاية الأرض ودمارها، ليظهر في يومنا الحاضر خلال مهمة لتحديد موقع وباء قاتل من شأنه أن يَدمّر الجنس البشري بالكامل",
      backgroundImage: "https://m.media-amazon.com/images/M/MV5BMTkwOTcxNzMzOV5BMl5BanBnXkFtZTgwODYxNjg0ODE@._V1_.jpg",
    },
    {
      id : 12,
      url : " فيلم-spiderman",
      rate: 3,
      title: "spiderman فيلم ",
      content: "يتناول الفيلم قصة طالب في المرحلة الثانوية يُدعي بيتر باركر. يعضه عنكبوت مُعالج جينياً، فيكتسب قدرات خارقة نتيجة امتزاج كود العنكبوت الجيني بالكود الخاص به",
      backgroundImage: "https://m.media-amazon.com/images/I/91ROGy7tYGL._AC_UF1000,1000_QL80_.jpg",
    },
    {
      id : 13,
      url : "مسلسل-the-walking-dead",
      rate: 8.6,
      title: "the walking deadمسلسل ",
      content: "مسلسل ذا ووكينج ديد زومبي واثارة مجموعة تحاول الهروب من الموت حيث تواجههم صعوبات في رحلتهم", 
      backgroundImage: "https://m.media-amazon.com/images/I/813QE3zGj4L._AC_UF1000,1000_QL80_.jpg",
      
    },
    {
      id : 14,
      url : "مسلسل-prison-break",
      rate: 10,
      title: "مسلسل prison break",
      content: "يقوم مايكل سكوفيلد باقحام نفسه ويدخل السجن لينقذ اخاه ويحاول الهرب من السجن وتواجههم بعض الصعوبات",
      backgroundImage: "https://m.media-amazon.com/images/I/51S7PUcgb2L._AC_UF894,1000_QL80_.jpg",
    },
    {
      id : 15,
      url : "مسلسل-Game-Of-Throans",
      rate: 9.8,
      title: "Game Of Throans مسلسل",
      content: "صراع العروش هو مسلسل تقوم احداثه في عصر التنانين تحارب الممالك السبع للحصول على العرش الحديدي",
      backgroundImage: "https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
    },
    {
      id : 16,
      url : "مسلسل-breaking-bad",
      rate : 6,
      title: "bp مسلسل      ",
      content: "اختلال ضال يحكي قصة والتر وايت (براين كرانستون)، معلم مادة الكيمياء في إحدى المدارس الثانوية، والذي يتم تشخيصه بأنه مصابٌ بمرض سرطان الرئة غير قابلٍ للعلاج في بداية المسلسل",
      backgroundImage: "https://static.displate.com/270x380/displate/2021-02-09/265eb60ddb098e964211e1cfc5c787f6_adfafdfc684d9a6c5e90f7d9e584fa82.jpg",
    },
    {
      id : 17,
      url : "مسلسل-12-monkeys",
      rate: 7.5,
      title: "12 monkeys مسلسل ",
      content: "تتبع المسلسل رحلة مسافر زمني أتى من مستقبل ما بعد نهاية الأرض ودمارها، ليظهر في يومنا الحاضر خلال مهمة لتحديد موقع وباء قاتل من شأنه أن يَدمّر الجنس البشري بالكامل",
      backgroundImage: "https://m.media-amazon.com/images/M/MV5BMTkwOTcxNzMzOV5BMl5BanBnXkFtZTgwODYxNjg0ODE@._V1_.jpg",
    },
    {
      id : 18,
      url : " فيلم-spiderman",
      rate: 3,
      title: "spiderman فيلم ",
      content: "يتناول الفيلم قصة طالب في المرحلة الثانوية يُدعي بيتر باركر. يعضه عنكبوت مُعالج جينياً، فيكتسب قدرات خارقة نتيجة امتزاج كود العنكبوت الجيني بالكود الخاص به",
      backgroundImage: "https://m.media-amazon.com/images/I/91ROGy7tYGL._AC_UF1000,1000_QL80_.jpg",
    },
    {
      id : 19,
      url : "مسلسل-the-walking-dead",
      rate: 8.6,
      title: "the walking deadمسلسل ",
      content: "مسلسل ذا ووكينج ديد زومبي واثارة مجموعة تحاول الهروب من الموت حيث تواجههم صعوبات في رحلتهم", 
      backgroundImage: "https://m.media-amazon.com/images/I/813QE3zGj4L._AC_UF1000,1000_QL80_.jpg",
      
    },
    {
      id : 20,
      url : "مسلسل-prison-break",
      rate: 10,
      title: "مسلسل prison break",
      content: "يقوم مايكل سكوفيلد باقحام نفسه ويدخل السجن لينقذ اخاه ويحاول الهرب من السجن وتواجههم بعض الصعوبات",
      backgroundImage: "https://m.media-amazon.com/images/I/51S7PUcgb2L._AC_UF894,1000_QL80_.jpg",
    },
    {
      id : 21,
      url : "مسلسل-Game-Of-Throans",
      rate: 9.8,
      title: "Game Of Throans مسلسل",
      content: "صراع العروش هو مسلسل تقوم احداثه في عصر التنانين تحارب الممالك السبع للحصول على العرش الحديدي",
      backgroundImage: "https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
    },
    {
      id : 22,
      url : "مسلسل-breaking-bad",
      rate : 6,
      title: "bp مسلسل      ",
      content: "اختلال ضال يحكي قصة والتر وايت (براين كرانستون)، معلم مادة الكيمياء في إحدى المدارس الثانوية، والذي يتم تشخيصه بأنه مصابٌ بمرض سرطان الرئة غير قابلٍ للعلاج في بداية المسلسل",
      backgroundImage: "https://static.displate.com/270x380/displate/2021-02-09/265eb60ddb098e964211e1cfc5c787f6_adfafdfc684d9a6c5e90f7d9e584fa82.jpg",
    },
    {
      id : 23,
      url : "مسلسل-12-monkeys",
      rate: 7.5,
      title: "12 monkeys مسلسل ",
      content: "تتبع المسلسل رحلة مسافر زمني أتى من مستقبل ما بعد نهاية الأرض ودمارها، ليظهر في يومنا الحاضر خلال مهمة لتحديد موقع وباء قاتل من شأنه أن يَدمّر الجنس البشري بالكامل",
      backgroundImage: "https://m.media-amazon.com/images/M/MV5BMTkwOTcxNzMzOV5BMl5BanBnXkFtZTgwODYxNjg0ODE@._V1_.jpg",
    },
    {
      id : 24,
      url : " فيلم-spiderman",
      rate: 3,
      title: "spiderman فيلم ",
      content: "يتناول الفيلم قصة طالب في المرحلة الثانوية يُدعي بيتر باركر. يعضه عنكبوت مُعالج جينياً، فيكتسب قدرات خارقة نتيجة امتزاج كود العنكبوت الجيني بالكود الخاص به",
      backgroundImage: "https://m.media-amazon.com/images/I/91ROGy7tYGL._AC_UF1000,1000_QL80_.jpg",
    },
    


    
  ];